apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.keycloak.hostname }}
        secretName: "{{ .Values.ingress.tls.secretName }}"
    {{ if .Values.ingress.enableSecondary }}
      - {{ .Values.keycloak.secondaryHostname }}
        secretName: "{{ .Values.ingress.tls.secretName }}"
    {{- end }}
  {{- end }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.keycloak.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ template "common.names.fullname" . }}
                port:
                  name: http
{{- if .Values.ingress.enableSecondary }}
    - host: {{ .Values.keycloak.secondaryHostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ template "common.names.fullname" . }}
                port:
                  name: http
{{- end }}
