{{- if .Values.ingress.admin.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-admin
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    # authentication type
    nginx.ingress.kubernetes.io/auth-type: "{{ .Values.ingress.admin.auth.type }}"
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: "{{ .Values.ingress.admin.auth.secret }}"
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: "{{ .Values.ingress.admin.auth.realm }}"
  {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - "{{ .Values.keycloak.hostname }}"
      {{- if .Values.ingress.tls.secretName }}
      secretName: "{{ .Values.ingress.tls.secretName }}"
      {{- end }}
  {{- end }}
  ingressClassName: "{{ .Values.ingress.ingressClassName }}"
  rules:
    - host: "{{ .Values.keycloak.hostname }}"
      http:
        paths:
          - path: "{{ $.Values.keycloak.httpRelativePath }}/admin"
            pathType: "Prefix"
            backend:
              service:
                name: "{{ include "common.names.fullname" $ }}"
                port:
                  name: "http"
{{- end }}
