{{- if and (not (empty .Values.ingress.admin.allowedIPs)) .Values.ingress.admin.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "common.names.fullname" . }}-ipallowlist
  namespace: {{ include "common.names.namespace" . }}
spec:
  ipAllowList:
    sourceRange:
      {{- .Values.ingress.admin.allowedIPs | toYaml | nindent 6 }}
{{- end }}
