#jinja2: trim_blocks:True, lstrip_blocks:True
replicaCount: {{ keycloak_replica_count }}
image:
  repository: "{{ keycloak_image_repository }}"
  tag: "{{ keycloak_image_tag }}"
  pullPolicy: "{{ keycloak_image_pull_policy }}"
  pullSecrets:
{% for secret in keycloak_image_pull_secrets %}
    - "{{ secret }}"
{% endfor %}

auth:
  existingSecret: "{{ keycloak_auth_existing_secret }}"
  secretName: "{{ keycloak_auth_secret_name }}"
  adminUsername: "{{ keycloak_auth_admin_username }}"
  adminPassword: "{{ keycloak_auth_admin_password }}"
  keycloakRs256PrivateKey: "{{ keycloak_auth_rs256_private_key }}"
  keycloakRs256Certificate: "{{ keycloak_auth_rs256_certificate }}"
  keycloakAdminSecret: "{{ keycloak_auth_admin_secret }}"
  keycloakClientSecret: "{{ keycloak_auth_client_secret }}"
  keycloakServiceClientCertificate: "{{ keycloak_auth_service_client_certificate }}"

importRealms: {{ keycloak_import_realms }}

command:
{% for command in keycloak_command %}
  - "{{ command }}"
{% endfor %}

test:
{% for value  in keycloak_hosts %}
  - name: "{{ value.name }}"
  {% if value.auth_only is defined %}
    authOnly: "{{ value.auth_only }}"
  {% else %}
    authOnly: "{{ keycloak_ingress_path_auth_only }}"
  {% endif %}
{% endfor %}
