apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "common.names.namespace" . }}
  labels: 
    {{- include "common.labels" . | nindent 4 }}
data:
  KC_DB_URL: "{{ .Values.database.url }}"
  KC_DB_USERNAME: "{{ .Values.database.username }}"
  KC_ROOT_URL: "https://{{ .Values.frontendHostname }}"
  KC_PROXY_HEADERS: "xforwarded"
  KC_HTTP_ENABLED: "{{ default .Values.service.http.enabled false }}"
  KEYCLOAK_ADMIN: admin
  KC_HTTP_MANAGEMENT_PORT: "8090"
  JAVA_OPTS_APPEND: "-Djgroups.dns.query={{ template "common.names.name" . }}-headless.{{ template "common.names.namespace" . }}.svc.cluster.local"
  KC_HTTP_POOL_MAX_THREADS: "{{ .Values.threadPool }}"
  # KC_DB_URL: "jdbc:postgresql://$(DB_HOST)/$(DB_NAME)"