name: ansible-lint
on:
  push:
    branches:
      - "**"

env:
  ANSIBLE_LINT_SARIF_FILE: "ansible-lint-results.sarif"

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read          # Required to checkout and read repo files
      security-events: write  # Required to upload SARIF files to Security tab
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
      - name: Run ansible-lint
        uses: ansible/ansible-lint@665d9e07a1943254d2910faffc106adaf7ea7294 # v26.8.0
        with:
          setup_python: "true"
          python_version: "3.14"
          # working_directory: "./ansible"
          requirements_file: "collections/requirements.yml"
          args: "--sarif-file ${{ env.ANSIBLE_LINT_SARIF_FILE }}"
      - name: upload ansible-lint results
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        with:
          sarif_file: "${{ env.ANSIBLE_LINT_SARIF_FILE }}"
