name: hadolint
on:
  push:
    branches:
      - "**"

env:
  HADOLINT_SARIF_FILE: "hadolint-results.sarif"

jobs:
  lint:
    name: Hadolint
    runs-on: ubuntu-latest
    permissions:
      contents: read          # Required to checkout and read repo files
      security-events: write  # Required to upload SARIF files to Security tab
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 1

      - name: Run hadolint
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5  # v3.3.0
        with:
          dockerfile: Dockerfile
          failure-threshold: "warning"
          output-file: "${{ env.HADOLINT_SARIF_FILE }}"
          format: "sarif"
          verbose: true
      - name: upload hadolint results
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        with:
          sarif_file: "${{ env.HADOLINT_SARIF_FILE }}"
