name: kubeconform

on:
  push:
    branches:
      - "**"

env:
  KUBECONFORM_SARIF_FILE: "kubeconform-results.sarif"
  KUBECONFORM_OUTPUT_FILE: "kubeconform-results.txt"
  HELM_OUTPUT_DIR: "helm-template"


jobs:
  lint:
    name: Kubeconform
    runs-on: ubuntu-latest
    permissions:
      contents: read          # Required to checkout and read repo files
      security-events: write  # Required to upload SARIF files to Security tab
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Set up Kubeconform
        run: go install github.com/yannh/kubeconform/cmd/kubeconform@e65429b1e5990dd019ebb7b5642dcd22a3e9cd13  # v0.7.0

      - name: Run Kubeconform
        run: |
          export PATH="$(go env GOPATH)/bin:${PATH}"
          set -o pipefail

          helm template --output-dir ${{ env.HELM_OUTPUT_DIR }} helm/dbp-keycloak

          kubeconform \
          -schema-location default \
          -schema-location \
          'https://raw.githubusercontent.com/datreeio/CRDs-catalog/'\
          '3348d879deb1cb95a5e93c1c206ffa4a0a494c2c/{{.Group}}/'\
          '{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' \
          -strict \
          -output json \
          ${{ env.HELM_OUTPUT_DIR }} \
          | tee ${{ env.KUBECONFORM_OUTPUT_FILE }}
          python3 kubeconform2sarif.py -r helm < ${{ env.KUBECONFORM_OUTPUT_FILE }} > ${{ env.KUBECONFORM_SARIF_FILE }}
      - name: upload kubeconform results
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        with:
          sarif_file: "${{ env.KUBECONFORM_SARIF_FILE }}"
