name: kubeconform

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Kubeconform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Set up Kubeconform
        run: go install github.com/yannh/kubeconform/cmd/kubeconform@latest

      - name: Run Kubeconform
        run: |
          echo "gopath $GOPATH"
          echo $PATH
          ls -liash /home/runner/go
          export PATH="$(go env GOPATH)/bin:${PATH}"
          echo $PATH
          helm template helm/dbp-keycloak | kubeconform -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' -strict
