name: trivy-code-scan

on:
  push:
    branches:
      - "**"

env:
  TRIVY_SCAN_SARIF_FILE: "trivy-results.sarif"

jobs:
  scan:
    name: Trivy Code Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read          # Required to checkout and read repo files
      security-events: write  # Required to upload SARIF files to Security tab
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: run trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: "config"
          format: "sarif"
          output: "${{ env.TRIVY_SCAN_SARIF_FILE }}"
          scan-ref: "."
          # exit-code: '1'
          # severity: "CRITICAL,HIGH"

      - name: upload trivy results
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        with:
          sarif_file: "${{ env.TRIVY_SCAN_SARIF_FILE }}"
